name: publish_to_ps_gallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - Source/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Publish to PSGallery, only if local version is greater than the online version
      - name: publish
        env:
          APIKEY: ${{ secrets.PSGalleryKey }}
        working-directory: Source
        run: |
            $OnlineVersion = (Find-Module 'SecretManagement.HcVault.KV2').Version
            $LocalVersion  = (Import-PowerShellDataFile SecretManagement.HcVault.KV2.psd1).ModuleVersion
            if ($LocalVersion -le $OnlineVersion) {return}
            Install-Module PowershellGet -Force -AllowPreRelease
            Remove-Module PowershellGet; Import-Module PowershellGet
            Publish-PSResource -Path . -ApiKey $env:APIKEY
