name: publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: publish
        env:
          APIKEY: ${{ secrets.PSGalleryKey }}
        working-directory: ./Source
        run:
          Publish-Module -Path . -NuGetApiKey $env:NUGETAPIKEY
